#ifndef UI_GUI_H
#define UI_GUI_H

// Autogenerated on: 09-07-2017 12:07:33 
#include <Wt/WFileResource>
#include <Wt/WContainerWidget>
#include <Wt/WGroupBox>
#include <Wt/WLineEdit>
#include <Wt/WPushButton>
#include <Wt/WText>
#include <Wt/WFileUpload>
#include <Wt/WBootstrapTheme>

class Ui_GUI
{

public:

	Wt::WContainerWidget *wt_root;
	Wt::WGroupBox *grpLogin;
	Wt::WContainerWidget *containerLogin;
	Wt::WLineEdit *edtUserLogin;
	Wt::WLineEdit *edtPassLogin;
	Wt::WPushButton *btnLogin;
	Wt::WText *txtWarninLogin;
	Wt::WGroupBox *grpEstudiante;
	Wt::WGroupBox *grpUsuarios;
	Wt::WGroupBox *grpAddUsuario;
	Wt::WContainerWidget *containerAddUsuarios;
	Wt::WLineEdit *edtAddUsuario;
	Wt::WLineEdit *edtAddPassUsuario;
	Wt::WLineEdit *edtAddTipoUsuario;
	Wt::WPushButton *btnAddUsuario;
	Wt::WGroupBox *grpEditUsuario;
	Wt::WContainerWidget *containerEditUsuarios;
	Wt::WLineEdit *edtEditUsuario;
	Wt::WLineEdit *edtEditPassUsuario;
	Wt::WLineEdit *edtEditTipoUsuario;
	Wt::WPushButton *btnEditUsuario;
	Wt::WGroupBox *grpDeleteUsuario;
	Wt::WContainerWidget *containerDeleteUsuarios;
	Wt::WLineEdit *edtDeleteUsuario;
	Wt::WPushButton *btnDeleteUsuario;
	Wt::WGroupBox *grpEdificios;
	Wt::WGroupBox *grpAddEdificio;
	Wt::WContainerWidget *containerAddEdificio;
	Wt::WLineEdit *edtAddNombreEdificio;
	Wt::WPushButton *btnAddEdificio;
	Wt::WGroupBox *grpEditEdificio;
	Wt::WContainerWidget *containerEditEdificio;
	Wt::WLineEdit *edtEditNombreEdificio;
	Wt::WPushButton *btnEditEdificio;
	Wt::WGroupBox *grpDeleteEdificio;
	Wt::WContainerWidget *containerDeleteEdificio;
	Wt::WLineEdit *edtDeleteCodigoEdificio;
	Wt::WPushButton *btnDeleteEdificio;
	Wt::WGroupBox *grpAddSalon;
	Wt::WContainerWidget *containerAddSalon;
	Wt::WLineEdit *edtAddEdificioSalon;
	Wt::WLineEdit *edtAddNumeroSalon;
	Wt::WLineEdit *edtAddCapacidadSalon;
	Wt::WPushButton *btnAddSalon;
	Wt::WGroupBox *grpEditSalon;
	Wt::WContainerWidget *containerEditSalon;
	Wt::WLineEdit *edtEditEdificioSalon;
	Wt::WLineEdit *edtEditNumeroSalon;
	Wt::WLineEdit *edtEditCapacidadSalon;
	Wt::WPushButton *btnEditSalon;
	Wt::WGroupBox *grpDeleteSalon;
	Wt::WContainerWidget *containerDeleteSalon;
	Wt::WLineEdit *edtDeleteCodigoSalon;
	Wt::WPushButton *btnDeleteSalon;
	Wt::WGroupBox *grpCursos;
	Wt::WGroupBox *grpAddCurso;
	Wt::WContainerWidget *containerAddCurso;
	Wt::WLineEdit *edtAddCodigoCurso;
	Wt::WLineEdit *edtAddNombreCurso;
	Wt::WLineEdit *edtAddSemestreCurso;
	Wt::WLineEdit *edtAddCreditoCurso;
	Wt::WPushButton *btnAddCurso;
	Wt::WGroupBox *grpEditCurso;
	Wt::WContainerWidget *containerEditCurso;
	Wt::WLineEdit *edtEditCodigoCurso;
	Wt::WLineEdit *edtEditNombreCurso;
	Wt::WLineEdit *edtEditSemestreCurso;
	Wt::WLineEdit *edtEditCreditoCurso;
	Wt::WPushButton *btnEditCurso;
	Wt::WGroupBox *grpDeleteCurso;
	Wt::WContainerWidget *containerDeleteCurso;
	Wt::WLineEdit *edtDeleteCodigoCurso;
	Wt::WPushButton *btnDeleteCurso;
	Wt::WGroupBox *grpEstudiantes;
	Wt::WGroupBox *grpAddEstudiante;
	Wt::WContainerWidget *containerAddEstudiante;
	Wt::WLineEdit *edtAddCarneEstudiante;
	Wt::WLineEdit *edtAddNombreEstudiante;
	Wt::WLineEdit *edtAddCiudadEstudiante;
	Wt::WPushButton *btnAddEstudiante;
	Wt::WGroupBox *grpEditEstudiante;
	Wt::WContainerWidget *containeEditEstudiante;
	Wt::WLineEdit *edtEditCarneEstudiante;
	Wt::WLineEdit *edtEditNombreEstudiante;
	Wt::WLineEdit *edtEditCiudadEstudiante;
	Wt::WPushButton *btnEditEstudiante;
	Wt::WGroupBox *grpDeleteEstudiante;
	Wt::WContainerWidget *containerDeleteEstudiante;
	Wt::WLineEdit *edtDeleteCarneEstudiante;
	Wt::WPushButton *btnDeleteEstudiante;
	Wt::WGroupBox *grpCatedraticos;
	Wt::WGroupBox *grpAddCatedratico;
	Wt::WContainerWidget *containerAddCatedratico;
	Wt::WLineEdit *edtAddCodigoCatedratico;
	Wt::WLineEdit *edtAddNombreCatedratico;
	Wt::WLineEdit *edtAddCiudadCatedratico;
	Wt::WPushButton *btnAddCatedratico;
	Wt::WGroupBox *grpEditCatedratico;
	Wt::WContainerWidget *containerEditCatedratico;
	Wt::WLineEdit *edtEditCodigoCatedratico;
	Wt::WLineEdit *edtEditNombreCatedratico;
	Wt::WLineEdit *edtEditCiudadCatedratico;
	Wt::WPushButton *btnEditCatedratico;
	Wt::WGroupBox *grpDeleteCatedratico;
	Wt::WContainerWidget *containerDeleteCatedratico;
	Wt::WLineEdit *edtDeleteCodigoCatedratico;
	Wt::WPushButton *btnDeleteCatedratico;
	Wt::WGroupBox *grpHorario;
	Wt::WGroupBox *grpAsignaciones;
	Wt::WGroupBox *grpReportes;
	Wt::WContainerWidget *containerReportes;
	Wt::WPushButton *btnGraficoUsuario;
	Wt::WPushButton *btnGraficoEyS;
	Wt::WPushButton *btnGraficoCursos;
	Wt::WPushButton *btnGraficoEstudiantes;
	Wt::WPushButton *btnGraficoCatedraticos;
	Wt::WPushButton *btnGraficoHorarios;
	Wt::WPushButton *btnGraficoAsignaciones;
	Wt::WGroupBox *grpArchivos;
	Wt::WContainerWidget *containerArchivos;
	Wt::WFileUpload *fileupload;

	void setupUi(Wt::WContainerWidget *PageRoot)
	{

		Wt::WBootstrapTheme * p_wtTheme = new Wt::WBootstrapTheme();
		p_wtTheme->setVersion(Wt::WBootstrapTheme::Version3);
		Wt::WApplication::instance()->setTheme(p_wtTheme);
		Wt::WApplication::instance()->setTitle("Untitled Wt Webapp");

		addAllStyleSheets();

		wt_root = (PageRoot);
		wt_root->setId("wt_root");
		wt_root->setStyleClass(Wt::WString::fromUTF8(""));
		wt_root->setInline(0);
		{
			grpLogin = new Wt::WGroupBox(wt_root);
			grpLogin->setId("grpLogin");
			grpLogin->setStyleClass(Wt::WString::fromUTF8("group"));
			grpLogin->setInline(0);
			grpLogin->setTitle(Wt::WString::fromUTF8("Inicio de Sesión"));
			{
				containerLogin = new Wt::WContainerWidget(grpLogin);
				containerLogin->setId("containerLogin");
				containerLogin->setStyleClass(Wt::WString::fromUTF8("container"));
				containerLogin->setInline(0);
				containerLogin->setHtmlTagName("div");
				{
					edtUserLogin = new Wt::WLineEdit(containerLogin);
					edtUserLogin->setId("edtUserLogin");
					edtUserLogin->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
					edtUserLogin->setInline(1);
					edtUserLogin->setEmptyText(Wt::WString::fromUTF8("Usuario"));
					edtPassLogin = new Wt::WLineEdit(containerLogin);
					edtPassLogin->setId("edtPassLogin");
					edtPassLogin->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
					edtPassLogin->setInline(1);
					edtPassLogin->setEmptyText(Wt::WString::fromUTF8("Contraseña"));
					btnLogin = new Wt::WPushButton(containerLogin);
					btnLogin->setId("btnLogin");
					btnLogin->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
					btnLogin->setInline(1);
					btnLogin->setEmptyText(Wt::WString::fromUTF8(""));
					btnLogin->setText(Wt::WString::fromUTF8("Login"));
					btnLogin->setLink(Wt::WLink(""));
					txtWarninLogin = new Wt::WText(containerLogin);
					txtWarninLogin->setId("txtWarninLogin");
					txtWarninLogin->setStyleClass(Wt::WString::fromUTF8("label-danger label item"));
					txtWarninLogin->setInline(0);
					txtWarninLogin->setTextFormat((Wt::TextFormat)0);
					txtWarninLogin->setText(Wt::WString::fromUTF8("¡Usuario o Contraseña incorrecta!"));
				}
			}
			grpEstudiante = new Wt::WGroupBox(wt_root);
			grpEstudiante->setId("grpEstudiante");
			grpEstudiante->setStyleClass(Wt::WString::fromUTF8("group"));
			grpEstudiante->setInline(0);
			grpEstudiante->setTitle(Wt::WString::fromUTF8("Estudiante"));
			grpUsuarios = new Wt::WGroupBox(wt_root);
			grpUsuarios->setId("grpUsuarios");
			grpUsuarios->setStyleClass(Wt::WString::fromUTF8("group"));
			grpUsuarios->setInline(0);
			grpUsuarios->setTitle(Wt::WString::fromUTF8("Gestión de usuarios"));
			{
				grpAddUsuario = new Wt::WGroupBox(grpUsuarios);
				grpAddUsuario->setId("grpAddUsuario");
				grpAddUsuario->setStyleClass(Wt::WString::fromUTF8("group subgroup"));
				grpAddUsuario->setInline(0);
				grpAddUsuario->setTitle(Wt::WString::fromUTF8("Agregar usuario"));
				{
					containerAddUsuarios = new Wt::WContainerWidget(grpAddUsuario);
					containerAddUsuarios->setId("containerAddUsuarios");
					containerAddUsuarios->setStyleClass(Wt::WString::fromUTF8("container"));
					containerAddUsuarios->setInline(0);
					containerAddUsuarios->setHtmlTagName("div");
					{
						edtAddUsuario = new Wt::WLineEdit(containerAddUsuarios);
						edtAddUsuario->setId("edtAddUsuario");
						edtAddUsuario->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtAddUsuario->setInline(1);
						edtAddUsuario->setEmptyText(Wt::WString::fromUTF8("Nombre de usuario"));
						edtAddPassUsuario = new Wt::WLineEdit(containerAddUsuarios);
						edtAddPassUsuario->setId("edtAddPassUsuario");
						edtAddPassUsuario->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtAddPassUsuario->setInline(1);
						edtAddPassUsuario->setEmptyText(Wt::WString::fromUTF8("Contraseña de usuario"));
						edtAddTipoUsuario = new Wt::WLineEdit(containerAddUsuarios);
						edtAddTipoUsuario->setId("edtAddTipoUsuario");
						edtAddTipoUsuario->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtAddTipoUsuario->setInline(1);
						edtAddTipoUsuario->setEmptyText(Wt::WString::fromUTF8("Tipo de usuario"));
						btnAddUsuario = new Wt::WPushButton(containerAddUsuarios);
						btnAddUsuario->setId("btnAddUsuario");
						btnAddUsuario->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
						btnAddUsuario->setInline(1);
						btnAddUsuario->setEmptyText(Wt::WString::fromUTF8(""));
						btnAddUsuario->setText(Wt::WString::fromUTF8("Agregar Usuario"));
						btnAddUsuario->setLink(Wt::WLink(""));
					}
				}
				grpEditUsuario = new Wt::WGroupBox(grpUsuarios);
				grpEditUsuario->setId("grpEditUsuario");
				grpEditUsuario->setStyleClass(Wt::WString::fromUTF8("group subgroup"));
				grpEditUsuario->setInline(0);
				grpEditUsuario->setTitle(Wt::WString::fromUTF8("Editar Usuario"));
				{
					containerEditUsuarios = new Wt::WContainerWidget(grpEditUsuario);
					containerEditUsuarios->setId("containerEditUsuarios");
					containerEditUsuarios->setStyleClass(Wt::WString::fromUTF8("container"));
					containerEditUsuarios->setInline(0);
					containerEditUsuarios->setHtmlTagName("div");
					{
						edtEditUsuario = new Wt::WLineEdit(containerEditUsuarios);
						edtEditUsuario->setId("edtEditUsuario");
						edtEditUsuario->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtEditUsuario->setInline(1);
						edtEditUsuario->setEmptyText(Wt::WString::fromUTF8("Nombre de usuario"));
						edtEditPassUsuario = new Wt::WLineEdit(containerEditUsuarios);
						edtEditPassUsuario->setId("edtEditPassUsuario");
						edtEditPassUsuario->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtEditPassUsuario->setInline(1);
						edtEditPassUsuario->setEmptyText(Wt::WString::fromUTF8("Contraseña de usuario"));
						edtEditTipoUsuario = new Wt::WLineEdit(containerEditUsuarios);
						edtEditTipoUsuario->setId("edtEditTipoUsuario");
						edtEditTipoUsuario->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtEditTipoUsuario->setInline(1);
						edtEditTipoUsuario->setEmptyText(Wt::WString::fromUTF8("Tipo de usuario"));
						btnEditUsuario = new Wt::WPushButton(containerEditUsuarios);
						btnEditUsuario->setId("btnEditUsuario");
						btnEditUsuario->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
						btnEditUsuario->setInline(1);
						btnEditUsuario->setEmptyText(Wt::WString::fromUTF8(""));
						btnEditUsuario->setText(Wt::WString::fromUTF8("Editar Usuario"));
						btnEditUsuario->setLink(Wt::WLink(""));
					}
				}
				grpDeleteUsuario = new Wt::WGroupBox(grpUsuarios);
				grpDeleteUsuario->setId("grpDeleteUsuario");
				grpDeleteUsuario->setStyleClass(Wt::WString::fromUTF8("group subgroup"));
				grpDeleteUsuario->setInline(0);
				grpDeleteUsuario->setTitle(Wt::WString::fromUTF8("Eliminar Usuario"));
				{
					containerDeleteUsuarios = new Wt::WContainerWidget(grpDeleteUsuario);
					containerDeleteUsuarios->setId("containerDeleteUsuarios");
					containerDeleteUsuarios->setStyleClass(Wt::WString::fromUTF8("container"));
					containerDeleteUsuarios->setInline(0);
					containerDeleteUsuarios->setHtmlTagName("div");
					{
						edtDeleteUsuario = new Wt::WLineEdit(containerDeleteUsuarios);
						edtDeleteUsuario->setId("edtDeleteUsuario");
						edtDeleteUsuario->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtDeleteUsuario->setInline(1);
						edtDeleteUsuario->setEmptyText(Wt::WString::fromUTF8("Nombre de usuario"));
						btnDeleteUsuario = new Wt::WPushButton(containerDeleteUsuarios);
						btnDeleteUsuario->setId("btnDeleteUsuario");
						btnDeleteUsuario->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
						btnDeleteUsuario->setInline(1);
						btnDeleteUsuario->setEmptyText(Wt::WString::fromUTF8(""));
						btnDeleteUsuario->setText(Wt::WString::fromUTF8("Eliminar Usuario"));
						btnDeleteUsuario->setLink(Wt::WLink(""));
					}
				}
			}
			grpEdificios = new Wt::WGroupBox(wt_root);
			grpEdificios->setId("grpEdificios");
			grpEdificios->setStyleClass(Wt::WString::fromUTF8("group"));
			grpEdificios->setInline(0);
			grpEdificios->setTitle(Wt::WString::fromUTF8("Gestión de edificios y salones"));
			{
				grpAddEdificio = new Wt::WGroupBox(grpEdificios);
				grpAddEdificio->setId("grpAddEdificio");
				grpAddEdificio->setStyleClass(Wt::WString::fromUTF8("group subgroup"));
				grpAddEdificio->setInline(0);
				grpAddEdificio->setTitle(Wt::WString::fromUTF8("Agregar Edificio"));
				{
					containerAddEdificio = new Wt::WContainerWidget(grpAddEdificio);
					containerAddEdificio->setId("containerAddEdificio");
					containerAddEdificio->setStyleClass(Wt::WString::fromUTF8("container"));
					containerAddEdificio->setInline(0);
					containerAddEdificio->setHtmlTagName("div");
					{
						edtAddNombreEdificio = new Wt::WLineEdit(containerAddEdificio);
						edtAddNombreEdificio->setId("edtAddNombreEdificio");
						edtAddNombreEdificio->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtAddNombreEdificio->setInline(1);
						edtAddNombreEdificio->setEmptyText(Wt::WString::fromUTF8("Nombre del Edificio"));
						btnAddEdificio = new Wt::WPushButton(containerAddEdificio);
						btnAddEdificio->setId("btnAddEdificio");
						btnAddEdificio->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
						btnAddEdificio->setInline(1);
						btnAddEdificio->setEmptyText(Wt::WString::fromUTF8(""));
						btnAddEdificio->setText(Wt::WString::fromUTF8("Agregar Edificio"));
						btnAddEdificio->setLink(Wt::WLink(""));
					}
				}
				grpEditEdificio = new Wt::WGroupBox(grpEdificios);
				grpEditEdificio->setId("grpEditEdificio");
				grpEditEdificio->setStyleClass(Wt::WString::fromUTF8("group subgroup"));
				grpEditEdificio->setInline(0);
				grpEditEdificio->setTitle(Wt::WString::fromUTF8("Editar Edificio"));
				{
					containerEditEdificio = new Wt::WContainerWidget(grpEditEdificio);
					containerEditEdificio->setId("containerEditEdificio");
					containerEditEdificio->setStyleClass(Wt::WString::fromUTF8("container"));
					containerEditEdificio->setInline(0);
					containerEditEdificio->setHtmlTagName("div");
					{
						edtEditNombreEdificio = new Wt::WLineEdit(containerEditEdificio);
						edtEditNombreEdificio->setId("edtEditNombreEdificio");
						edtEditNombreEdificio->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtEditNombreEdificio->setInline(1);
						edtEditNombreEdificio->setEmptyText(Wt::WString::fromUTF8("Nombre del Edificio"));
						btnEditEdificio = new Wt::WPushButton(containerEditEdificio);
						btnEditEdificio->setId("btnEditEdificio");
						btnEditEdificio->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
						btnEditEdificio->setInline(1);
						btnEditEdificio->setEmptyText(Wt::WString::fromUTF8(""));
						btnEditEdificio->setText(Wt::WString::fromUTF8("Editar Edificio"));
						btnEditEdificio->setLink(Wt::WLink(""));
					}
				}
				grpDeleteEdificio = new Wt::WGroupBox(grpEdificios);
				grpDeleteEdificio->setId("grpDeleteEdificio");
				grpDeleteEdificio->setStyleClass(Wt::WString::fromUTF8("group subgroup"));
				grpDeleteEdificio->setInline(0);
				grpDeleteEdificio->setTitle(Wt::WString::fromUTF8("Eliminar Edificio"));
				{
					containerDeleteEdificio = new Wt::WContainerWidget(grpDeleteEdificio);
					containerDeleteEdificio->setId("containerDeleteEdificio");
					containerDeleteEdificio->setStyleClass(Wt::WString::fromUTF8("container"));
					containerDeleteEdificio->setInline(0);
					containerDeleteEdificio->setHtmlTagName("div");
					{
						edtDeleteCodigoEdificio = new Wt::WLineEdit(containerDeleteEdificio);
						edtDeleteCodigoEdificio->setId("edtDeleteCodigoEdificio");
						edtDeleteCodigoEdificio->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtDeleteCodigoEdificio->setInline(1);
						edtDeleteCodigoEdificio->setEmptyText(Wt::WString::fromUTF8("Codigot del Edificio"));
						btnDeleteEdificio = new Wt::WPushButton(containerDeleteEdificio);
						btnDeleteEdificio->setId("btnDeleteEdificio");
						btnDeleteEdificio->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
						btnDeleteEdificio->setInline(1);
						btnDeleteEdificio->setEmptyText(Wt::WString::fromUTF8(""));
						btnDeleteEdificio->setText(Wt::WString::fromUTF8("Eliminar Edificio"));
						btnDeleteEdificio->setLink(Wt::WLink(""));
					}
				}
				grpAddSalon = new Wt::WGroupBox(grpEdificios);
				grpAddSalon->setId("grpAddSalon");
				grpAddSalon->setStyleClass(Wt::WString::fromUTF8("group subgroup"));
				grpAddSalon->setInline(0);
				grpAddSalon->setTitle(Wt::WString::fromUTF8("Agregar Salon"));
				{
					containerAddSalon = new Wt::WContainerWidget(grpAddSalon);
					containerAddSalon->setId("containerAddSalon");
					containerAddSalon->setStyleClass(Wt::WString::fromUTF8("container"));
					containerAddSalon->setInline(0);
					containerAddSalon->setHtmlTagName("div");
					{
						edtAddEdificioSalon = new Wt::WLineEdit(containerAddSalon);
						edtAddEdificioSalon->setId("edtAddEdificioSalon");
						edtAddEdificioSalon->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtAddEdificioSalon->setInline(1);
						edtAddEdificioSalon->setEmptyText(Wt::WString::fromUTF8("Edificio"));
						edtAddNumeroSalon = new Wt::WLineEdit(containerAddSalon);
						edtAddNumeroSalon->setId("edtAddNumeroSalon");
						edtAddNumeroSalon->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtAddNumeroSalon->setInline(1);
						edtAddNumeroSalon->setEmptyText(Wt::WString::fromUTF8("Numero del Salon"));
						edtAddCapacidadSalon = new Wt::WLineEdit(containerAddSalon);
						edtAddCapacidadSalon->setId("edtAddCapacidadSalon");
						edtAddCapacidadSalon->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtAddCapacidadSalon->setInline(1);
						edtAddCapacidadSalon->setEmptyText(Wt::WString::fromUTF8("Capacidad del Salon"));
						btnAddSalon = new Wt::WPushButton(containerAddSalon);
						btnAddSalon->setId("btnAddSalon");
						btnAddSalon->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
						btnAddSalon->setInline(1);
						btnAddSalon->setEmptyText(Wt::WString::fromUTF8(""));
						btnAddSalon->setText(Wt::WString::fromUTF8("Agregar Salon"));
						btnAddSalon->setLink(Wt::WLink(""));
					}
				}
				grpEditSalon = new Wt::WGroupBox(grpEdificios);
				grpEditSalon->setId("grpEditSalon");
				grpEditSalon->setStyleClass(Wt::WString::fromUTF8("group subgroup"));
				grpEditSalon->setInline(0);
				grpEditSalon->setTitle(Wt::WString::fromUTF8("Editar Salon"));
				{
					containerEditSalon = new Wt::WContainerWidget(grpEditSalon);
					containerEditSalon->setId("containerEditSalon");
					containerEditSalon->setStyleClass(Wt::WString::fromUTF8("container"));
					containerEditSalon->setInline(0);
					containerEditSalon->setHtmlTagName("div");
					{
						edtEditEdificioSalon = new Wt::WLineEdit(containerEditSalon);
						edtEditEdificioSalon->setId("edtEditEdificioSalon");
						edtEditEdificioSalon->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtEditEdificioSalon->setInline(1);
						edtEditEdificioSalon->setEmptyText(Wt::WString::fromUTF8("Edificio del Salon"));
						edtEditNumeroSalon = new Wt::WLineEdit(containerEditSalon);
						edtEditNumeroSalon->setId("edtEditNumeroSalon");
						edtEditNumeroSalon->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtEditNumeroSalon->setInline(1);
						edtEditNumeroSalon->setEmptyText(Wt::WString::fromUTF8("Numero del Salon"));
						edtEditCapacidadSalon = new Wt::WLineEdit(containerEditSalon);
						edtEditCapacidadSalon->setId("edtEditCapacidadSalon");
						edtEditCapacidadSalon->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtEditCapacidadSalon->setInline(1);
						edtEditCapacidadSalon->setEmptyText(Wt::WString::fromUTF8("Capacidad del Salon"));
						btnEditSalon = new Wt::WPushButton(containerEditSalon);
						btnEditSalon->setId("btnEditSalon");
						btnEditSalon->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
						btnEditSalon->setInline(1);
						btnEditSalon->setEmptyText(Wt::WString::fromUTF8(""));
						btnEditSalon->setText(Wt::WString::fromUTF8("Editar Salon"));
						btnEditSalon->setLink(Wt::WLink(""));
					}
				}
				grpDeleteSalon = new Wt::WGroupBox(grpEdificios);
				grpDeleteSalon->setId("grpDeleteSalon");
				grpDeleteSalon->setStyleClass(Wt::WString::fromUTF8("group subgroup"));
				grpDeleteSalon->setInline(0);
				grpDeleteSalon->setTitle(Wt::WString::fromUTF8("Eliminar Salon"));
				{
					containerDeleteSalon = new Wt::WContainerWidget(grpDeleteSalon);
					containerDeleteSalon->setId("containerDeleteSalon");
					containerDeleteSalon->setStyleClass(Wt::WString::fromUTF8("container"));
					containerDeleteSalon->setInline(0);
					containerDeleteSalon->setHtmlTagName("div");
					{
						edtDeleteCodigoSalon = new Wt::WLineEdit(containerDeleteSalon);
						edtDeleteCodigoSalon->setId("edtDeleteCodigoSalon");
						edtDeleteCodigoSalon->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtDeleteCodigoSalon->setInline(1);
						edtDeleteCodigoSalon->setEmptyText(Wt::WString::fromUTF8("Codigo del Salon"));
						btnDeleteSalon = new Wt::WPushButton(containerDeleteSalon);
						btnDeleteSalon->setId("btnDeleteSalon");
						btnDeleteSalon->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
						btnDeleteSalon->setInline(1);
						btnDeleteSalon->setEmptyText(Wt::WString::fromUTF8(""));
						btnDeleteSalon->setText(Wt::WString::fromUTF8("Eliminar Salon"));
						btnDeleteSalon->setLink(Wt::WLink(""));
					}
				}
			}
			grpCursos = new Wt::WGroupBox(wt_root);
			grpCursos->setId("grpCursos");
			grpCursos->setStyleClass(Wt::WString::fromUTF8("group"));
			grpCursos->setInline(0);
			grpCursos->setTitle(Wt::WString::fromUTF8("Gestión de cursos"));
			{
				grpAddCurso = new Wt::WGroupBox(grpCursos);
				grpAddCurso->setId("grpAddCurso");
				grpAddCurso->setStyleClass(Wt::WString::fromUTF8("group subgroup"));
				grpAddCurso->setInline(0);
				grpAddCurso->setTitle(Wt::WString::fromUTF8("Agregar Curso"));
				{
					containerAddCurso = new Wt::WContainerWidget(grpAddCurso);
					containerAddCurso->setId("containerAddCurso");
					containerAddCurso->setStyleClass(Wt::WString::fromUTF8("container"));
					containerAddCurso->setInline(0);
					containerAddCurso->setHtmlTagName("div");
					{
						edtAddCodigoCurso = new Wt::WLineEdit(containerAddCurso);
						edtAddCodigoCurso->setId("edtAddCodigoCurso");
						edtAddCodigoCurso->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtAddCodigoCurso->setInline(1);
						edtAddCodigoCurso->setEmptyText(Wt::WString::fromUTF8("Número de Código"));
						edtAddNombreCurso = new Wt::WLineEdit(containerAddCurso);
						edtAddNombreCurso->setId("edtAddNombreCurso");
						edtAddNombreCurso->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtAddNombreCurso->setInline(1);
						edtAddNombreCurso->setEmptyText(Wt::WString::fromUTF8("Nombre del Curso"));
						edtAddSemestreCurso = new Wt::WLineEdit(containerAddCurso);
						edtAddSemestreCurso->setId("edtAddSemestreCurso");
						edtAddSemestreCurso->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtAddSemestreCurso->setInline(1);
						edtAddSemestreCurso->setEmptyText(Wt::WString::fromUTF8("Semestre del Curso"));
						edtAddCreditoCurso = new Wt::WLineEdit(containerAddCurso);
						edtAddCreditoCurso->setId("edtAddCreditoCurso");
						edtAddCreditoCurso->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtAddCreditoCurso->setInline(1);
						edtAddCreditoCurso->setEmptyText(Wt::WString::fromUTF8("Creditos del Curso"));
						btnAddCurso = new Wt::WPushButton(containerAddCurso);
						btnAddCurso->setId("btnAddCurso");
						btnAddCurso->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
						btnAddCurso->setInline(1);
						btnAddCurso->setEmptyText(Wt::WString::fromUTF8(""));
						btnAddCurso->setText(Wt::WString::fromUTF8("Agregar Curso"));
						btnAddCurso->setLink(Wt::WLink(""));
					}
				}
				grpEditCurso = new Wt::WGroupBox(grpCursos);
				grpEditCurso->setId("grpEditCurso");
				grpEditCurso->setStyleClass(Wt::WString::fromUTF8("group subgroup"));
				grpEditCurso->setInline(0);
				grpEditCurso->setTitle(Wt::WString::fromUTF8("Editar Curso"));
				{
					containerEditCurso = new Wt::WContainerWidget(grpEditCurso);
					containerEditCurso->setId("containerEditCurso");
					containerEditCurso->setStyleClass(Wt::WString::fromUTF8("container"));
					containerEditCurso->setInline(0);
					containerEditCurso->setHtmlTagName("div");
					{
						edtEditCodigoCurso = new Wt::WLineEdit(containerEditCurso);
						edtEditCodigoCurso->setId("edtEditCodigoCurso");
						edtEditCodigoCurso->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtEditCodigoCurso->setInline(1);
						edtEditCodigoCurso->setEmptyText(Wt::WString::fromUTF8("Número de Código"));
						edtEditNombreCurso = new Wt::WLineEdit(containerEditCurso);
						edtEditNombreCurso->setId("edtEditNombreCurso");
						edtEditNombreCurso->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtEditNombreCurso->setInline(1);
						edtEditNombreCurso->setEmptyText(Wt::WString::fromUTF8("Nombre del Curso"));
						edtEditSemestreCurso = new Wt::WLineEdit(containerEditCurso);
						edtEditSemestreCurso->setId("edtEditSemestreCurso");
						edtEditSemestreCurso->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtEditSemestreCurso->setInline(1);
						edtEditSemestreCurso->setEmptyText(Wt::WString::fromUTF8("Semestre del Curso"));
						edtEditCreditoCurso = new Wt::WLineEdit(containerEditCurso);
						edtEditCreditoCurso->setId("edtEditCreditoCurso");
						edtEditCreditoCurso->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtEditCreditoCurso->setInline(1);
						edtEditCreditoCurso->setEmptyText(Wt::WString::fromUTF8("Creditos del Curso"));
						btnEditCurso = new Wt::WPushButton(containerEditCurso);
						btnEditCurso->setId("btnEditCurso");
						btnEditCurso->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
						btnEditCurso->setInline(1);
						btnEditCurso->setEmptyText(Wt::WString::fromUTF8(""));
						btnEditCurso->setText(Wt::WString::fromUTF8("Editar Curso"));
						btnEditCurso->setLink(Wt::WLink(""));
					}
				}
				grpDeleteCurso = new Wt::WGroupBox(grpCursos);
				grpDeleteCurso->setId("grpDeleteCurso");
				grpDeleteCurso->setStyleClass(Wt::WString::fromUTF8("group subgroup"));
				grpDeleteCurso->setInline(0);
				grpDeleteCurso->setTitle(Wt::WString::fromUTF8("Eliminar Curso"));
				{
					containerDeleteCurso = new Wt::WContainerWidget(grpDeleteCurso);
					containerDeleteCurso->setId("containerDeleteCurso");
					containerDeleteCurso->setStyleClass(Wt::WString::fromUTF8("container"));
					containerDeleteCurso->setInline(0);
					containerDeleteCurso->setHtmlTagName("div");
					{
						edtDeleteCodigoCurso = new Wt::WLineEdit(containerDeleteCurso);
						edtDeleteCodigoCurso->setId("edtDeleteCodigoCurso");
						edtDeleteCodigoCurso->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtDeleteCodigoCurso->setInline(1);
						edtDeleteCodigoCurso->setEmptyText(Wt::WString::fromUTF8("Código del Curso"));
						btnDeleteCurso = new Wt::WPushButton(containerDeleteCurso);
						btnDeleteCurso->setId("btnDeleteCurso");
						btnDeleteCurso->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
						btnDeleteCurso->setInline(1);
						btnDeleteCurso->setEmptyText(Wt::WString::fromUTF8(""));
						btnDeleteCurso->setText(Wt::WString::fromUTF8("Eliminar Curso"));
						btnDeleteCurso->setLink(Wt::WLink(""));
					}
				}
			}
			grpEstudiantes = new Wt::WGroupBox(wt_root);
			grpEstudiantes->setId("grpEstudiantes");
			grpEstudiantes->setStyleClass(Wt::WString::fromUTF8("group"));
			grpEstudiantes->setInline(0);
			grpEstudiantes->setTitle(Wt::WString::fromUTF8("Gestión de estudiantes"));
			{
				grpAddEstudiante = new Wt::WGroupBox(grpEstudiantes);
				grpAddEstudiante->setId("grpAddEstudiante");
				grpAddEstudiante->setStyleClass(Wt::WString::fromUTF8("group subgroup"));
				grpAddEstudiante->setInline(0);
				grpAddEstudiante->setTitle(Wt::WString::fromUTF8("Agregar Estudiante"));
				{
					containerAddEstudiante = new Wt::WContainerWidget(grpAddEstudiante);
					containerAddEstudiante->setId("containerAddEstudiante");
					containerAddEstudiante->setStyleClass(Wt::WString::fromUTF8("container"));
					containerAddEstudiante->setInline(0);
					containerAddEstudiante->setHtmlTagName("div");
					{
						edtAddCarneEstudiante = new Wt::WLineEdit(containerAddEstudiante);
						edtAddCarneEstudiante->setId("edtAddCarneEstudiante");
						edtAddCarneEstudiante->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtAddCarneEstudiante->setInline(1);
						edtAddCarneEstudiante->setEmptyText(Wt::WString::fromUTF8("Número de carnet"));
						edtAddNombreEstudiante = new Wt::WLineEdit(containerAddEstudiante);
						edtAddNombreEstudiante->setId("edtAddNombreEstudiante");
						edtAddNombreEstudiante->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtAddNombreEstudiante->setInline(1);
						edtAddNombreEstudiante->setEmptyText(Wt::WString::fromUTF8("Nombre del estudiante"));
						edtAddCiudadEstudiante = new Wt::WLineEdit(containerAddEstudiante);
						edtAddCiudadEstudiante->setId("edtAddCiudadEstudiante");
						edtAddCiudadEstudiante->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtAddCiudadEstudiante->setInline(1);
						edtAddCiudadEstudiante->setEmptyText(Wt::WString::fromUTF8("Ciudad del estudiante"));
						btnAddEstudiante = new Wt::WPushButton(containerAddEstudiante);
						btnAddEstudiante->setId("btnAddEstudiante");
						btnAddEstudiante->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
						btnAddEstudiante->setInline(1);
						btnAddEstudiante->setEmptyText(Wt::WString::fromUTF8(""));
						btnAddEstudiante->setText(Wt::WString::fromUTF8("Agregar Estudiante"));
						btnAddEstudiante->setLink(Wt::WLink(""));
					}
				}
				grpEditEstudiante = new Wt::WGroupBox(grpEstudiantes);
				grpEditEstudiante->setId("grpEditEstudiante");
				grpEditEstudiante->setStyleClass(Wt::WString::fromUTF8("group subgroup"));
				grpEditEstudiante->setInline(0);
				grpEditEstudiante->setTitle(Wt::WString::fromUTF8("Editar Estudiante"));
				{
					containeEditEstudiante = new Wt::WContainerWidget(grpEditEstudiante);
					containeEditEstudiante->setId("containeEditEstudiante");
					containeEditEstudiante->setStyleClass(Wt::WString::fromUTF8("container"));
					containeEditEstudiante->setInline(0);
					containeEditEstudiante->setHtmlTagName("div");
					{
						edtEditCarneEstudiante = new Wt::WLineEdit(containeEditEstudiante);
						edtEditCarneEstudiante->setId("edtEditCarneEstudiante");
						edtEditCarneEstudiante->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtEditCarneEstudiante->setInline(1);
						edtEditCarneEstudiante->setEmptyText(Wt::WString::fromUTF8("Número de carnet"));
						edtEditNombreEstudiante = new Wt::WLineEdit(containeEditEstudiante);
						edtEditNombreEstudiante->setId("edtEditNombreEstudiante");
						edtEditNombreEstudiante->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtEditNombreEstudiante->setInline(1);
						edtEditNombreEstudiante->setEmptyText(Wt::WString::fromUTF8("Nombre del estudiante"));
						edtEditCiudadEstudiante = new Wt::WLineEdit(containeEditEstudiante);
						edtEditCiudadEstudiante->setId("edtEditCiudadEstudiante");
						edtEditCiudadEstudiante->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtEditCiudadEstudiante->setInline(1);
						edtEditCiudadEstudiante->setEmptyText(Wt::WString::fromUTF8("Ciudad del estudiante"));
						btnEditEstudiante = new Wt::WPushButton(containeEditEstudiante);
						btnEditEstudiante->setId("btnEditEstudiante");
						btnEditEstudiante->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
						btnEditEstudiante->setInline(1);
						btnEditEstudiante->setEmptyText(Wt::WString::fromUTF8(""));
						btnEditEstudiante->setText(Wt::WString::fromUTF8("Editar Estudiante"));
						btnEditEstudiante->setLink(Wt::WLink(""));
					}
				}
				grpDeleteEstudiante = new Wt::WGroupBox(grpEstudiantes);
				grpDeleteEstudiante->setId("grpDeleteEstudiante");
				grpDeleteEstudiante->setStyleClass(Wt::WString::fromUTF8("group subgroup"));
				grpDeleteEstudiante->setInline(0);
				grpDeleteEstudiante->setTitle(Wt::WString::fromUTF8("Eliminar Estudiante"));
				{
					containerDeleteEstudiante = new Wt::WContainerWidget(grpDeleteEstudiante);
					containerDeleteEstudiante->setId("containerDeleteEstudiante");
					containerDeleteEstudiante->setStyleClass(Wt::WString::fromUTF8("container"));
					containerDeleteEstudiante->setInline(0);
					containerDeleteEstudiante->setHtmlTagName("div");
					{
						edtDeleteCarneEstudiante = new Wt::WLineEdit(containerDeleteEstudiante);
						edtDeleteCarneEstudiante->setId("edtDeleteCarneEstudiante");
						edtDeleteCarneEstudiante->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtDeleteCarneEstudiante->setInline(1);
						edtDeleteCarneEstudiante->setEmptyText(Wt::WString::fromUTF8("Carnet del estudiante"));
						btnDeleteEstudiante = new Wt::WPushButton(containerDeleteEstudiante);
						btnDeleteEstudiante->setId("btnDeleteEstudiante");
						btnDeleteEstudiante->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
						btnDeleteEstudiante->setInline(1);
						btnDeleteEstudiante->setEmptyText(Wt::WString::fromUTF8(""));
						btnDeleteEstudiante->setText(Wt::WString::fromUTF8("Eliminar Estudiante"));
						btnDeleteEstudiante->setLink(Wt::WLink(""));
					}
				}
			}
			grpCatedraticos = new Wt::WGroupBox(wt_root);
			grpCatedraticos->setId("grpCatedraticos");
			grpCatedraticos->setStyleClass(Wt::WString::fromUTF8("group"));
			grpCatedraticos->setInline(0);
			grpCatedraticos->setTitle(Wt::WString::fromUTF8("Gestión de catedráticos"));
			{
				grpAddCatedratico = new Wt::WGroupBox(grpCatedraticos);
				grpAddCatedratico->setId("grpAddCatedratico");
				grpAddCatedratico->setStyleClass(Wt::WString::fromUTF8("group subgroup"));
				grpAddCatedratico->setInline(0);
				grpAddCatedratico->setTitle(Wt::WString::fromUTF8("Agregar Catedratico"));
				{
					containerAddCatedratico = new Wt::WContainerWidget(grpAddCatedratico);
					containerAddCatedratico->setId("containerAddCatedratico");
					containerAddCatedratico->setStyleClass(Wt::WString::fromUTF8("container"));
					containerAddCatedratico->setInline(0);
					containerAddCatedratico->setHtmlTagName("div");
					{
						edtAddCodigoCatedratico = new Wt::WLineEdit(containerAddCatedratico);
						edtAddCodigoCatedratico->setId("edtAddCodigoCatedratico");
						edtAddCodigoCatedratico->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtAddCodigoCatedratico->setInline(1);
						edtAddCodigoCatedratico->setEmptyText(Wt::WString::fromUTF8("Código del Catedrático"));
						edtAddNombreCatedratico = new Wt::WLineEdit(containerAddCatedratico);
						edtAddNombreCatedratico->setId("edtAddNombreCatedratico");
						edtAddNombreCatedratico->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtAddNombreCatedratico->setInline(1);
						edtAddNombreCatedratico->setEmptyText(Wt::WString::fromUTF8("Nombre del Catedratico"));
						edtAddCiudadCatedratico = new Wt::WLineEdit(containerAddCatedratico);
						edtAddCiudadCatedratico->setId("edtAddCiudadCatedratico");
						edtAddCiudadCatedratico->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtAddCiudadCatedratico->setInline(1);
						edtAddCiudadCatedratico->setEmptyText(Wt::WString::fromUTF8("Ciudad del Catedratico"));
						btnAddCatedratico = new Wt::WPushButton(containerAddCatedratico);
						btnAddCatedratico->setId("btnAddCatedratico");
						btnAddCatedratico->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
						btnAddCatedratico->setInline(1);
						btnAddCatedratico->setEmptyText(Wt::WString::fromUTF8(""));
						btnAddCatedratico->setText(Wt::WString::fromUTF8("Agregar Catedratico"));
						btnAddCatedratico->setLink(Wt::WLink(""));
					}
				}
				grpEditCatedratico = new Wt::WGroupBox(grpCatedraticos);
				grpEditCatedratico->setId("grpEditCatedratico");
				grpEditCatedratico->setStyleClass(Wt::WString::fromUTF8("group subgroup"));
				grpEditCatedratico->setInline(0);
				grpEditCatedratico->setTitle(Wt::WString::fromUTF8("Editar Catedratico"));
				{
					containerEditCatedratico = new Wt::WContainerWidget(grpEditCatedratico);
					containerEditCatedratico->setId("containerEditCatedratico");
					containerEditCatedratico->setStyleClass(Wt::WString::fromUTF8("container"));
					containerEditCatedratico->setInline(0);
					containerEditCatedratico->setHtmlTagName("div");
					{
						edtEditCodigoCatedratico = new Wt::WLineEdit(containerEditCatedratico);
						edtEditCodigoCatedratico->setId("edtEditCodigoCatedratico");
						edtEditCodigoCatedratico->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtEditCodigoCatedratico->setInline(1);
						edtEditCodigoCatedratico->setEmptyText(Wt::WString::fromUTF8("Código del Catedrático"));
						edtEditNombreCatedratico = new Wt::WLineEdit(containerEditCatedratico);
						edtEditNombreCatedratico->setId("edtEditNombreCatedratico");
						edtEditNombreCatedratico->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtEditNombreCatedratico->setInline(1);
						edtEditNombreCatedratico->setEmptyText(Wt::WString::fromUTF8("Nombre del Catedratico"));
						edtEditCiudadCatedratico = new Wt::WLineEdit(containerEditCatedratico);
						edtEditCiudadCatedratico->setId("edtEditCiudadCatedratico");
						edtEditCiudadCatedratico->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtEditCiudadCatedratico->setInline(1);
						edtEditCiudadCatedratico->setEmptyText(Wt::WString::fromUTF8("Ciudad del Catedratico"));
						btnEditCatedratico = new Wt::WPushButton(containerEditCatedratico);
						btnEditCatedratico->setId("btnEditCatedratico");
						btnEditCatedratico->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
						btnEditCatedratico->setInline(1);
						btnEditCatedratico->setEmptyText(Wt::WString::fromUTF8(""));
						btnEditCatedratico->setText(Wt::WString::fromUTF8("Editar Catedratico"));
						btnEditCatedratico->setLink(Wt::WLink(""));
					}
				}
				grpDeleteCatedratico = new Wt::WGroupBox(grpCatedraticos);
				grpDeleteCatedratico->setId("grpDeleteCatedratico");
				grpDeleteCatedratico->setStyleClass(Wt::WString::fromUTF8("group subgroup"));
				grpDeleteCatedratico->setInline(0);
				grpDeleteCatedratico->setTitle(Wt::WString::fromUTF8("Eliminar Catedratico"));
				{
					containerDeleteCatedratico = new Wt::WContainerWidget(grpDeleteCatedratico);
					containerDeleteCatedratico->setId("containerDeleteCatedratico");
					containerDeleteCatedratico->setStyleClass(Wt::WString::fromUTF8("container"));
					containerDeleteCatedratico->setInline(0);
					containerDeleteCatedratico->setHtmlTagName("div");
					{
						edtDeleteCodigoCatedratico = new Wt::WLineEdit(containerDeleteCatedratico);
						edtDeleteCodigoCatedratico->setId("edtDeleteCodigoCatedratico");
						edtDeleteCodigoCatedratico->setStyleClass(Wt::WString::fromUTF8("form-control item form-control"));
						edtDeleteCodigoCatedratico->setInline(1);
						edtDeleteCodigoCatedratico->setEmptyText(Wt::WString::fromUTF8("Código del Catedratico"));
						btnDeleteCatedratico = new Wt::WPushButton(containerDeleteCatedratico);
						btnDeleteCatedratico->setId("btnDeleteCatedratico");
						btnDeleteCatedratico->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
						btnDeleteCatedratico->setInline(1);
						btnDeleteCatedratico->setEmptyText(Wt::WString::fromUTF8(""));
						btnDeleteCatedratico->setText(Wt::WString::fromUTF8("Eliminar Catedratico"));
						btnDeleteCatedratico->setLink(Wt::WLink(""));
					}
				}
			}
			grpHorario = new Wt::WGroupBox(wt_root);
			grpHorario->setId("grpHorario");
			grpHorario->setStyleClass(Wt::WString::fromUTF8("group"));
			grpHorario->setInline(0);
			grpHorario->setTitle(Wt::WString::fromUTF8("Gestión de horarios"));
			grpAsignaciones = new Wt::WGroupBox(wt_root);
			grpAsignaciones->setId("grpAsignaciones");
			grpAsignaciones->setStyleClass(Wt::WString::fromUTF8("group"));
			grpAsignaciones->setInline(0);
			grpAsignaciones->setTitle(Wt::WString::fromUTF8("Gestión de asignaciones"));
			grpReportes = new Wt::WGroupBox(wt_root);
			grpReportes->setId("grpReportes");
			grpReportes->setStyleClass(Wt::WString::fromUTF8("group"));
			grpReportes->setInline(0);
			grpReportes->setTitle(Wt::WString::fromUTF8("Reportes"));
			{
				containerReportes = new Wt::WContainerWidget(grpReportes);
				containerReportes->setId("containerReportes");
				containerReportes->setStyleClass(Wt::WString::fromUTF8("container"));
				containerReportes->setInline(0);
				containerReportes->setHtmlTagName("div");
				{
					btnGraficoUsuario = new Wt::WPushButton(containerReportes);
					btnGraficoUsuario->setId("btnGraficoUsuario");
					btnGraficoUsuario->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
					btnGraficoUsuario->setInline(1);
					btnGraficoUsuario->setEmptyText(Wt::WString::fromUTF8(""));
					btnGraficoUsuario->setText(Wt::WString::fromUTF8("Usuario"));
					btnGraficoUsuario->setLink(Wt::WLink(""));
					btnGraficoEyS = new Wt::WPushButton(containerReportes);
					btnGraficoEyS->setId("btnGraficoEyS");
					btnGraficoEyS->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
					btnGraficoEyS->setInline(1);
					btnGraficoEyS->setEmptyText(Wt::WString::fromUTF8(""));
					btnGraficoEyS->setText(Wt::WString::fromUTF8("Edificios y Salones"));
					btnGraficoEyS->setLink(Wt::WLink(""));
					btnGraficoCursos = new Wt::WPushButton(containerReportes);
					btnGraficoCursos->setId("btnGraficoCursos");
					btnGraficoCursos->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
					btnGraficoCursos->setInline(1);
					btnGraficoCursos->setEmptyText(Wt::WString::fromUTF8(""));
					btnGraficoCursos->setText(Wt::WString::fromUTF8("Cursos"));
					btnGraficoCursos->setLink(Wt::WLink(""));
					btnGraficoEstudiantes = new Wt::WPushButton(containerReportes);
					btnGraficoEstudiantes->setId("btnGraficoEstudiantes");
					btnGraficoEstudiantes->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
					btnGraficoEstudiantes->setInline(1);
					btnGraficoEstudiantes->setEmptyText(Wt::WString::fromUTF8(""));
					btnGraficoEstudiantes->setText(Wt::WString::fromUTF8("Estudiantes"));
					btnGraficoEstudiantes->setLink(Wt::WLink(""));
					btnGraficoCatedraticos = new Wt::WPushButton(containerReportes);
					btnGraficoCatedraticos->setId("btnGraficoCatedraticos");
					btnGraficoCatedraticos->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
					btnGraficoCatedraticos->setInline(1);
					btnGraficoCatedraticos->setEmptyText(Wt::WString::fromUTF8(""));
					btnGraficoCatedraticos->setText(Wt::WString::fromUTF8("Catedráticos"));
					btnGraficoCatedraticos->setLink(Wt::WLink(""));
					btnGraficoHorarios = new Wt::WPushButton(containerReportes);
					btnGraficoHorarios->setId("btnGraficoHorarios");
					btnGraficoHorarios->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
					btnGraficoHorarios->setInline(1);
					btnGraficoHorarios->setEmptyText(Wt::WString::fromUTF8(""));
					btnGraficoHorarios->setText(Wt::WString::fromUTF8("Horarios"));
					btnGraficoHorarios->setLink(Wt::WLink(""));
					btnGraficoAsignaciones = new Wt::WPushButton(containerReportes);
					btnGraficoAsignaciones->setId("btnGraficoAsignaciones");
					btnGraficoAsignaciones->setStyleClass(Wt::WString::fromUTF8("btn-default with-label btn-primary btn item btn btn-default with-label"));
					btnGraficoAsignaciones->setInline(1);
					btnGraficoAsignaciones->setEmptyText(Wt::WString::fromUTF8(""));
					btnGraficoAsignaciones->setText(Wt::WString::fromUTF8("Asignaciones"));
					btnGraficoAsignaciones->setLink(Wt::WLink(""));
				}
			}
			grpArchivos = new Wt::WGroupBox(wt_root);
			grpArchivos->setId("grpArchivos");
			grpArchivos->setStyleClass(Wt::WString::fromUTF8("group"));
			grpArchivos->setInline(0);
			grpArchivos->setTitle(Wt::WString::fromUTF8("Selector de archivos"));
			{
				containerArchivos = new Wt::WContainerWidget(grpArchivos);
				containerArchivos->setId("containerArchivos");
				containerArchivos->setStyleClass(Wt::WString::fromUTF8("container"));
				containerArchivos->setInline(0);
				containerArchivos->setHtmlTagName("div");
				{
					fileupload = new Wt::WFileUpload(containerArchivos);
					fileupload->setId("fileupload");
					fileupload->setStyleClass(Wt::WString::fromUTF8("fileupload item"));
					fileupload->setInline(0);
				}
			}
		}

		connectAllSignals();

		addAllJavaScripts();

	}


	void addAllStyleSheets()
	{

		Wt::WApplication::instance()->useStyleSheet(Wt::WLink("resources/main.css"));

	}


	void addAllJavaScripts()
	{


	}


	void connectAllSignals()
	{


	}


};

#endif // UI_GUI_H